//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataObjects.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUser
    {
        public AspNetUser()
        {
            this.AccountTypes = new HashSet<AccountType>();
            this.AspNetUserClaims = new HashSet<AspNetUserClaim>();
            this.AspNetUserLogins = new HashSet<AspNetUserLogin>();
            this.AspNetUserRoles = new HashSet<AspNetUserRole>();
            this.ReceiptChangeHistories = new HashSet<ReceiptChangeHistory>();
            this.ReceiptImages = new HashSet<ReceiptImage>();
            this.Receipts = new HashSet<Receipt>();
            this.ReceiptCategories = new HashSet<ReceiptCategory>();
            this.RentalIncomeDetails = new HashSet<RentalIncomeDetail>();
            this.TaxUsers = new HashSet<TaxUser>();
            this.UserPermissions = new HashSet<UserPermission>();
            this.UserPermissions1 = new HashSet<UserPermission>();
            this.Vendors = new HashSet<Vendor>();
        }
    
        public string Id { get; set; }
        public string UserName { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string Discriminator { get; set; }
        public string Email { get; set; }
        public bool IsConfirmed { get; set; }
        public string ConfirmationToken { get; set; }
    
        public virtual ICollection<AccountType> AccountTypes { get; set; }
        public virtual ICollection<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual ICollection<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual ICollection<AspNetUserRole> AspNetUserRoles { get; set; }
        public virtual ICollection<ReceiptChangeHistory> ReceiptChangeHistories { get; set; }
        public virtual ICollection<ReceiptImage> ReceiptImages { get; set; }
        public virtual ICollection<Receipt> Receipts { get; set; }
        public virtual ICollection<ReceiptCategory> ReceiptCategories { get; set; }
        public virtual ICollection<RentalIncomeDetail> RentalIncomeDetails { get; set; }
        public virtual ICollection<TaxUser> TaxUsers { get; set; }
        public virtual ICollection<UserPermission> UserPermissions { get; set; }
        public virtual ICollection<UserPermission> UserPermissions1 { get; set; }
        public virtual ICollection<Vendor> Vendors { get; set; }
    }
}
