//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataObjects.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepreciationMethod
    {
        public DepreciationMethod()
        {
            this.DepreciationAssets = new HashSet<DepreciationAsset>();
            this.DepreciationBuildings = new HashSet<DepreciationBuilding>();
        }
    
        public int Id { get; set; }
        public string Method { get; set; }
    
        public virtual ICollection<DepreciationAsset> DepreciationAssets { get; set; }
        public virtual ICollection<DepreciationBuilding> DepreciationBuildings { get; set; }
    }
}
