//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataObjects.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepreciationAsset
    {
        public int Id { get; set; }
        public decimal OpeningAdjustedTaxValue { get; set; }
        public int DepreciationMethod_Id { get; set; }
        public decimal RatePercentage { get; set; }
        public decimal DepreciationClaimed { get; set; }
        public decimal CloseingAdjustedTaxValue { get; set; }
        public decimal NumberOfMonth { get; set; }
        public decimal PercentageUsage { get; set; }
        public string Note { get; set; }
        public int RentalIncomeDetail_Id { get; set; }
        public int Receipt_Id { get; set; }
    
        public virtual DepreciationMethod DepreciationMethod { get; set; }
        public virtual Receipt Receipt { get; set; }
        public virtual RentalIncomeDetail RentalIncomeDetail { get; set; }
    }
}
