//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataObjects.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disposal
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Value { get; set; }
        public string Note { get; set; }
        public int Receipt_Id { get; set; }
        public int DisposalType_Id { get; set; }
    
        public virtual DisposalType DisposalType { get; set; }
        public virtual Receipt Receipt { get; set; }
    }
}
