//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataObjects.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LMateDbContext : DbContext
    {
        public LMateDbContext(string connectionString)
            : base(connectionString)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Currencies> Currencies { get; set; }
        public virtual DbSet<DepreciationAssets> DepreciationAssets { get; set; }
        public virtual DbSet<DepreciationBuildings> DepreciationBuildings { get; set; }
        public virtual DbSet<DepreciationMethond> DepreciationMethond { get; set; }
        public virtual DbSet<Disposals> Disposals { get; set; }
        public virtual DbSet<DisposalType> DisposalType { get; set; }
        public virtual DbSet<Receipts> Receipts { get; set; }
        public virtual DbSet<ReceiptStatus> ReceiptStatus { get; set; }
        public virtual DbSet<ReceiptTypes> ReceiptTypes { get; set; }
        public virtual DbSet<RentalIncomeDetails> RentalIncomeDetails { get; set; }
        public virtual DbSet<TaxUsers> TaxUsers { get; set; }
        public virtual DbSet<UserDelegates> UserDelegates { get; set; }
    }
}
