//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataObjects.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt
    {
        public Receipt()
        {
            this.DepreciationAssets = new HashSet<DepreciationAsset>();
            this.Disposals = new HashSet<Disposal>();
            this.ReceiptChangeHistories = new HashSet<ReceiptChangeHistory>();
            this.ReceiptImages = new HashSet<ReceiptImage>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public string Reference { get; set; }
        public bool IsBulk { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<decimal> Price { get; set; }
        public bool IsIncludeTax { get; set; }
        public bool IsTaxExclusive { get; set; }
        public Nullable<decimal> GstRate { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public string Note { get; set; }
        public Nullable<int> Vendor_Id { get; set; }
        public Nullable<int> ReceiptCategory_Id { get; set; }
        public Nullable<int> ReceiptStatus_Id { get; set; }
        public Nullable<int> Currency_Id { get; set; }
        public Nullable<int> AccountType_Id { get; set; }
        public string User_Id { get; set; }
        public byte[] Version { get; set; }
    
        public virtual AccountType AccountType { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<DepreciationAsset> DepreciationAssets { get; set; }
        public virtual ICollection<Disposal> Disposals { get; set; }
        public virtual ReceiptCategory ReceiptCategory { get; set; }
        public virtual ICollection<ReceiptChangeHistory> ReceiptChangeHistories { get; set; }
        public virtual Vendor Vendor { get; set; }
        public virtual ICollection<ReceiptImage> ReceiptImages { get; set; }
    }
}
