//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataObjects.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptCategories
    {
        public ReceiptCategories()
        {
            this.Receipts = new HashSet<Receipts>();
        }
    
        public int Id { get; set; }
        public string Type { get; set; }
        public string User_Id { get; set; }
        public byte[] Version { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual ICollection<Receipts> Receipts { get; set; }
    }
}
