//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataObjects.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipts
    {
        public Receipts()
        {
            this.DepreciationAssets = new HashSet<DepreciationAssets>();
            this.Disposals = new HashSet<Disposals>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public string Reference { get; set; }
        public bool IsBulk { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<decimal> Price { get; set; }
        public bool IsIncludeTax { get; set; }
        public bool IsTaxExclusive { get; set; }
        public Nullable<decimal> GstRate { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public string Note { get; set; }
        public string Vendor_Id { get; set; }
        public Nullable<int> ReceiptCategory_Id { get; set; }
        public Nullable<int> ReceiptStatus_Id { get; set; }
        public Nullable<int> Currency_Id { get; set; }
        public Nullable<int> AccountType_Id { get; set; }
        public string User_Id { get; set; }
        public byte[] Version { get; set; }
    
        public virtual AccountTypes AccountTypes { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual ICollection<DepreciationAssets> DepreciationAssets { get; set; }
        public virtual ICollection<Disposals> Disposals { get; set; }
        public virtual ReceiptCategories ReceiptCategories { get; set; }
        public virtual ReceiptStatuses ReceiptStatuses { get; set; }
        public virtual Vendors Vendors { get; set; }
    }
}
