//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataObjects.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptChangeHistory
    {
        public int Id { get; set; }
        public int Receipt_Id { get; set; }
        public string Updater_Id { get; set; }
        public System.DateTime Date { get; set; }
        public string Changes { get; set; }
        public string Details { get; set; }
        public byte[] Version { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Receipt Receipt { get; set; }
    }
}
