//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataObjects.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxUsers
    {
        public TaxUsers()
        {
            this.RentalIncomeDetails = new HashSet<RentalIncomeDetails>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string IRDNumber { get; set; }
        public string Address { get; set; }
        public string User_Id { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual ICollection<RentalIncomeDetails> RentalIncomeDetails { get; set; }
    }
}
