//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataObjects.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxUser
    {
        public TaxUser()
        {
            this.RentalIncomeDetails = new HashSet<RentalIncomeDetail>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string IRDNumber { get; set; }
        public string Address { get; set; }
        public string User_Id { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<RentalIncomeDetail> RentalIncomeDetails { get; set; }
    }
}
