//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMate.DataObjects.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepreciationMethond
    {
        public DepreciationMethond()
        {
            this.DepreciationAssets = new HashSet<DepreciationAssets>();
            this.DepreciationBuildings = new HashSet<DepreciationBuildings>();
        }
    
        public int Id { get; set; }
        public string Methond { get; set; }
    
        public virtual ICollection<DepreciationAssets> DepreciationAssets { get; set; }
        public virtual ICollection<DepreciationBuildings> DepreciationBuildings { get; set; }
    }
}
