//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMate.DataObjects.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisposalType
    {
        public DisposalType()
        {
            this.Disposals = new HashSet<Disposals>();
        }
    
        public int Id { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<Disposals> Disposals { get; set; }
    }
}
