//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMate.DataObjects.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentalIncomeDetails
    {
        public RentalIncomeDetails()
        {
            this.DepreciationBuildings = new HashSet<DepreciationBuildings>();
        }
    
        public int Id { get; set; }
        public decimal YearEnded { get; set; }
        public string AddressOfPropertyRented { get; set; }
        public decimal PeriodThePropertyWasAvailableForRenting { get; set; }
        public decimal TotalRents { get; set; }
        public decimal OtherIncome { get; set; }
        public string OtherIncomeSpecify { get; set; }
        public decimal GainOrLossOnDisposal { get; set; }
        public decimal TotalIncome { get; set; }
        public decimal Rates { get; set; }
        public decimal Insurance { get; set; }
        public decimal Interest { get; set; }
        public decimal AgentCollectionFees { get; set; }
        public decimal TotalExpenses { get; set; }
        public decimal NetRent { get; set; }
        public string Note { get; set; }
        public int TaxUser_Id { get; set; }
        public string User_Id { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual ICollection<DepreciationBuildings> DepreciationBuildings { get; set; }
        public virtual TaxUsers TaxUsers { get; set; }
    }
}
